### ISSUE TITLE
Is a universal model suitable for all LR faces possible?

### ISSUE THREAD

**Issue by XiangyuWu** [tyshiwo/FSRNet#1]
Hi, tyshiwo!

Thanks for your great work. When implementing your project, it confused me that why different models are needed for different dataset? As shown in your paper, the only input requested for this network in the test stage is just a LR image. Are there great differences between Helen dataset and celeba dataset, for example, the crop strategy, which lead to different models needed?
And I test helen dataset with celeba model and the contray, it turned out that different models for different datasets are indeed needed.

**Comment by tyshiwo** [comment]
Hi, thanks for your interests on our work.

Different datasets may have different distributions, which requires different models for the best performance. However, if different datasets share similar distribution, one model may be enough. 

In our case, the celeba model may be better, since it is trained by a larger dataset.

**Comment by XiangyuWu** [comment]
You are quite right. 

I also let the LR images in Helen dataset go through the helen model twice, say I put the generative images to the network on the second round, and found it not perform well, while the same experiment with celeba dataset on its model would achieve better results.

In this respect, celeba model did perform more power generalization ability.

**Comment by XiangyuWu** [comment]
You are quite right, and sorry that I made a mistake just now...
